services:
  # Frontend Service (React/Next.js/Vue)
  - type: web
    name: frontend
    runtime: docker
    envVars:
      - key: PORT
        value: 3000

  # Backend Service
  - type: web
    name: backend
    runtime: docker
    envVars:
      - key: PORT
        value: 3001
      - key: DB_HOST
        fromDatabase:
          name: todolist_db
          property: host
      - key: DB_PORT
        value: 3306  # Using static value since MySQL default port is 3306
      - key: DB_NAME
        value: todolist
      - key: DB_USER
        value: root  # Using your specified root user
      - key: DB_PASS
        value: Rafa@123  # Using your specified password

  - type: pserv
    name: todolist_db
    plan: standard
    env: docker
    autoDeploy: false
    disk:
      name: mysql_data
      mountPath: /var/lib/mysql
      sizeGB: 10
    envVars:
    - fromGroup: mysql_config

envVarGroups:
- name: mysql_config
  envVars:
  - key: MYSQL_DATABASE
    value: todolist
  - key: MYSQL_USER
    value: root
  - key: MYSQL_PASSWORD
    value: Rafa@123
  - key: MYSQL_ROOT_PASSWORD
    value: Rafa@123
