services:
  # Frontend Service (React/Next.js/Vue)
  - type: web
    name: frontend
    runtime: docker
    rootDir: frontend
    # dockerfilePath: ./Dockerfile
  
  - type: web
    name: backend
    runtime: docker
    rootDir: backend
    # dockerfile: ./Dockerfile
    envVars:
      - key: PORT
        value: 3001
      - key: DB_HOST
        fromDatabase:
          name: todolist_db
          property: hostname
      - key: DB_PORT
        value: 3306
      - key: DB_NAME
        value: todolist
      - key: DB_USER
        value: root
      - key: DB_PASS
        fromDatabase:
          name: todolist_db
          property: password

  - type: pserv
    name: mysql
    plan: standard
    env: docker
    autoDeploy: false
    disk:
      name: mysql
      mountPath: /var/lib/mysql
      sizeGB: 10
    envVars:
    - fromGroup: mysql

envVarGroups:
- name: mysql
  envVars:
  - key: MYSQL_DATABASE
    value: mysql
  - key: MYSQL_USER
    value: root 
  - key: MYSQL_ROOT_PASSWORD
    value: Rafa@123