services:
  # Frontend Service (React/Next.js/Vue)
  - type: web
    name: frontend
    runtime: docker
    envVars:
      - key: PORT
        value: 3000

  # Backend Service
  - type: web
    name: backend
    runtime: docker
    envVars:
      - key: PORT
        value: 3001
      - key: DB_HOST
        fromDatabase:
          name: todolist_db
          property: host
      - key: DB_PORT
        value: 3306 
      - key: DB_NAME
        value: todolist
      - key: DB_USER
        value: root 
      - key: DB_PASS
        value: Rafa@123  

  - type: web
    name: mysql_temp
    runtime: docker
    image: mysql:8.0.21
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: Rafa@123
      - key: MYSQL_DATABASE 
        value: todolist 
      - key: MYSQL_USER
        value: root
      - key: MYSQL_PASSWORD
        value: Rafa@123


